SELECT V.PROGRAM, count(1) as NOs ,C.PRIORITY
--select C.STATUS_CODE, count(1) FROM FND_CONC_REQ_SUMMARY_V V, FND_CONCURRENT_REQUESTS C 
--SELECT V.REQUESTOR, count(1) 
FROM FND_CONC_REQ_SUMMARY_V V, FND_CONCURRENT_REQUESTS C WHERE V.REQUEST_ID = C.REQUEST_ID 
--AND V.PROGRAM = 'GEWSH Pick confirm program - APL (GEWSH Pick confirm program - APL)' 
--AND V.PROGRAM like 'GEQP%' 
AND C.STATUS_CODE = 'R' 
--AND C.PHASE_CODE = 'R' 
--group by V.REQUESTOR 
--AND V.REQUESTOR='515121729' 
--AND trunc(V.ACTUAL_START_DATE)='30-OCT-21' 
--group by V.PROGRAM 
group by V.PROGRAM,C.PRIORITY order by 2 desc;
