SELECT
  r.PATCH_RUN_ID,
  j.SESSION_ID,
  j.TASK_NUMBER AS TASK_NUM,
  j.JOB_NAME,
  j.PRODUCT,
  j.WORKER_ID AS W_ID,
  j.PHASE,
  j.PHASE_NAME,
  j.START_TIME,
  j.END_TIME,
  ROUND((j.ELAPSED_TIME * 24 * 60 * 60) / 3600, 2) AS E_HRS,
  j.RESTART_COUNT AS R_CNT,
  j.SUBDIRECTORY,
  j.LAST_UPDATE_DATE,
  PA.ATTRIBUTE_VALUE || '/adwork' || LPAD(j.WORKER_ID, 3, '0') || '.log' AS LOG_LOC
FROM
  APPLSYS.AD_PATCH_RUN_SESS_ATTRIBS PA,
  APPLSYS.AD_PROGRAM_RUN_TASK_JOBS j
  JOIN APPLSYS.AD_PATCH_RUNS r
    ON j.SESSION_ID = r.SESSION_ID
  JOIN (
    SELECT DISTINCT PATCHRUN_ID
    FROM APPLSYS.AD_ADOP_SESSION_PATCHES
    WHERE BUG_NUMBER = '36119925'
  ) p
    ON r.PATCH_RUN_ID = p.PATCHRUN_ID
WHERE
  PA.ATTRIBUTE_NAME = 'LOG_FILE_PATH'
  AND PA.SESSION_ID = j.SESSION_ID
ORDER BY
  j.ELAPSED_TIME DESC;
