-- This can be used to retrive the Patch Log locations and other attributes

SELECT DISTINCT ASP.BUG_NUMBER,ASP.PATCHRUN_ID , APR.SESSION_ID ,APRSA.ATTRIBUTE_NAME, APRSA.ATTRIBUTE_VALUE
FROM APPLSYS.AD_ADOP_SESSION_PATCHES ASP , APPLSYS.AD_PATCH_RUNS APR , APPLSYS.AD_PATCH_RUN_SESS_ATTRIBS APRSA
WHERE ASP.BUG_NUMBER IN ('36119925','36303698','36989014','37988551','37964268')
AND APR.PATCH_RUN_ID=ASP.PATCHRUN_ID
AND APR.SESSION_ID=APRSA.SESSION_ID;
