-- This query can be run only when ADOP Patching is in progress

SELECT WORKER_ID, CONTROL_CODE, STATUS, COMMAND, FILE_PRODUCT, SUBDIRECTORY, FILENAME, PHASE, END_TIME, RESTART_TIME, ELAPSED_TIME 
FROM APPLSYS.FND_INSTALL_PROCESSES;
